ALTER TABLE market_research_criteria
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS target_min NUMERIC,
  ADD COLUMN IF NOT EXISTS target_max NUMERIC,
  ADD COLUMN IF NOT EXISTS target_unit TEXT,
  ADD COLUMN IF NOT EXISTS target_label TEXT;

DELETE FROM market_research_scores WHERE id IS NOT NULL;
DELETE FROM market_research_criteria WHERE id IS NOT NULL;

INSERT INTO market_research_criteria (name, description, category, sort_order, weight, value_type, target_min, target_max, target_unit, target_label, is_active) VALUES
  ('Median Household Income', 'Median HHI ≥ 2.5x national (~$200k).', 'demographics', 110, 1.00, 'currency', 200000, NULL, '$', NULL, TRUE),
  ('Average Household Income', 'Average household income above $130k.', 'demographics', 120, 1.00, 'currency', 130000, NULL, '$', NULL, TRUE),
  ('Median Single-Family Home Price', 'Median SFH price exceeds $1.5M.', 'demographics', 130, 1.00, 'currency', 1500000, NULL, '$', NULL, TRUE),
  ('Households Earning $200k+', '≥35% of households earn over $200k.', 'demographics', 140, 1.00, 'percent', 35, NULL, '%', NULL, TRUE),
  ('Town Population', 'Town population between 5,000 and 75,000.', 'demographics', 150, 1.00, 'number', 5000, 75000, 'count', NULL, TRUE),
  ('10-Year Population Growth', 'Population growth 2–8% over the past decade (stable but not transient).', 'demographics', 160, 1.00, 'percent', 2, 8, '%', NULL, TRUE),
  ('Life Expectancy', 'Life expectancy 81–85 years.', 'demographics', 170, 1.00, 'number', 81, 85, 'years', NULL, TRUE),
  ('Low-Density Zoning Policies', 'Restrictive zoning that limits new supply (large lot minimums, low FAR).', 'governance', 210, 1.00, 'text', NULL, NULL, NULL, 'Restrictive', TRUE),
  ('Building Limitations / Moratoriums', 'Active building caps, height limits, or moratoria in place.', 'governance', 220, 1.00, 'text', NULL, NULL, NULL, 'Active restrictions', TRUE),
  ('Buildout Ratio', 'Developed land / developable land ≥ 95% (little room left to build).', 'governance', 230, 1.00, 'percent', 95, NULL, '%', NULL, TRUE),
  ('Historic Districts', 'Designated historic district(s) protecting character and limiting redevelopment.', 'governance', 240, 1.00, 'text', NULL, NULL, NULL, 'Designated districts', TRUE),
  ('Presidential Voter Turnout', 'Voter turnout >75% (engaged civic base).', 'governance', 250, 1.00, 'percent', 75, NULL, '%', NULL, TRUE),
  ('Municipal Credit Rating', 'Municipal credit rating AA or better.', 'governance', 260, 1.00, 'text', NULL, NULL, NULL, 'AA or better', TRUE),
  ('Moderate Tax Policies', 'Moderate city/state tax burden — not punitive on high earners.', 'governance', 270, 1.00, 'text', NULL, NULL, NULL, 'Moderate burden', TRUE),
  ('Fortune 1000 HQs within 25 miles', 'At least 10 Fortune 1000 headquarters within 25 miles.', 'economic_activity', 310, 1.00, 'number', 10, NULL, 'count', NULL, TRUE),
  ('Company Concentrations', 'Density of high-revenue / high-employment companies in priority industries (financial services, tech, pharma, biotech, PE/VC, family offices, hedge funds, professional services).', 'economic_activity', 315, 1.00, 'text', NULL, NULL, NULL, 'High density', TRUE),
  ('Executive Concentrations', 'Concentrations of senior executives — hedge fund, family offices, biotech, PE, academia, federal contracting, law, lobbying, financial services, energy, finance, technology, pharmaceuticals, aviation.', 'economic_activity', 320, 1.00, 'text', NULL, NULL, NULL, 'High density', TRUE),
  ('Proximity to Executive Jet Services', 'Executive jet airport within 30 minutes / 30 miles.', 'economic_activity', 330, 1.00, 'number', NULL, 30, 'miles', NULL, TRUE),
  ('Top 500 National Schools', 'Public or private schools ranked in the national Top 500.', 'education', 410, 1.00, 'text', NULL, NULL, NULL, 'Top 500', TRUE),
  ('High School Graduation Rate', 'High school graduation rate ≥ 94%.', 'education', 420, 1.00, 'percent', 94, NULL, '%', NULL, TRUE),
  ('Math / Reading Proficiency', 'Math & reading proficiency 1.5–2.0x the state average.', 'education', 430, 1.00, 'text', NULL, NULL, NULL, '1.5–2.0x state avg', TRUE),
  ('AP Participation', 'Advanced Placement participation ≥ 50%.', 'education', 440, 1.00, 'percent', 50, NULL, '%', NULL, TRUE),
  ('Bachelor''s Degree Attainment', 'Adults 25+ with a bachelor''s degree ≥ 70%.', 'education', 450, 1.00, 'percent', 70, NULL, '%', NULL, TRUE),
  ('Professional / Graduate Degrees', 'Adults 25+ with a professional or graduate degree ≥ 30%.', 'education', 460, 1.00, 'percent', 30, NULL, '%', NULL, TRUE),
  ('Violent Crime', 'Violent crime rate >75% below the national average.', 'quality_of_life', 510, 1.00, 'text', NULL, NULL, NULL, '>75% below national', TRUE),
  ('Property Crime', 'Property crime rate >50% below the national average.', 'quality_of_life', 520, 1.00, 'text', NULL, NULL, NULL, '>50% below national', TRUE),
  ('Overall Safety', 'Overall safety ranks in the Top 20% nationally.', 'quality_of_life', 530, 1.00, 'text', NULL, NULL, NULL, 'Top 20% nationally', TRUE),
  ('Happiness Rankings', 'Located in a state ranked Top 20 on ''Happiest States'' indices.', 'quality_of_life', 540, 1.00, 'text', NULL, NULL, NULL, 'Top 20 state', TRUE),
  ('Parks per 10,000 Residents', 'At least 2.5 parks per 10,000 residents.', 'quality_of_life', 550, 1.00, 'number', 2.5, NULL, 'parks/10k', NULL, TRUE),
  ('Arts & Cultural Venues', 'At least one major museum, theatre, arts venue, or major park system.', 'quality_of_life', 560, 1.00, 'text', NULL, NULL, NULL, '≥1 major venue', TRUE),
  ('Waterfront / Open Space (bonus)', 'Bonus: waterfront access or substantial open space.', 'quality_of_life', 570, 1.00, 'text', NULL, NULL, NULL, 'Bonus', TRUE),
  ('Recreational Programs', 'Well-funded recreational programs (YMCA, arboretums, playhouses).', 'quality_of_life', 580, 1.00, 'text', NULL, NULL, NULL, 'Well-funded', TRUE),
  ('Niche.com Town Grade', 'Niche.com town grade A or A+.', 'quality_of_life', 590, 1.00, 'text', NULL, NULL, NULL, 'A or A+', TRUE),
  ('Commute to Major Metro', '45-min door-to-door commute / reverse-commute to a major metro.', 'transit', 610, 1.00, 'number', NULL, 45, 'minutes', NULL, TRUE),
  ('Commute to Executive Jet Services', '30-min commute to executive jet services.', 'transit', 620, 1.00, 'number', NULL, 30, 'minutes', NULL, TRUE),
  ('Mass Transit Rail Access (bonus)', 'Bonus for proximity to mass transit rail.', 'transit', 630, 1.00, 'text', NULL, NULL, NULL, 'Bonus', TRUE);
