-- CRED iQ loan layer for Market Research (2026-09-23)
-- One row per loan note (same loan can sit in several CMBS deals as pari-passu notes).
CREATE TABLE IF NOT EXISTS market_loans (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  market_id          UUID REFERENCES market_research_markets(id) ON DELETE SET NULL,
  source             TEXT NOT NULL DEFAULT 'crediq',
  source_loan_id     TEXT NOT NULL,
  source_location_id TEXT,
  source_url         TEXT,
  loan_name          TEXT,
  property_name      TEXT,
  address            TEXT,
  city               TEXT,
  state              TEXT,
  zip                TEXT,
  latitude           NUMERIC,
  longitude          NUMERIC,
  property_type      TEXT,
  property_subtype   TEXT,
  building_size      NUMERIC,
  size_unit          TEXT,
  year_built         INT,
  year_renovated     INT,
  deal_name          TEXT NOT NULL DEFAULT '',
  deal_type          TEXT,
  originator         TEXT,
  origination_date   DATE,
  maturity_date      DATE,
  original_balance   NUMERIC,
  current_balance    NUMERIC,
  whole_loan_balance NUMERIC,
  mortgage_rate      NUMERIC,
  rate_type          TEXT,
  amortization       TEXT,
  io_periods         INT,
  prepay_desc        TEXT,
  lockout_end_date   DATE,
  payment_status     TEXT,
  watchlist          BOOLEAN,
  watchlist_reason   TEXT,
  special_serviced   BOOLEAN,
  ss_transfer_date   DATE,
  ss_reason          TEXT,
  workout_strategy   TEXT,
  modified           BOOLEAN,
  appraisal_date     DATE,
  appraised_value    NUMERIC,
  uw_noi             NUMERIC,
  uw_ncf             NUMERIC,
  latest_noi         NUMERIC,
  latest_dscr        NUMERIC,
  latest_occupancy   NUMERIC,
  financials_as_of   DATE,
  ltv                NUMERIC,
  debt_yield         NUMERIC,
  master_servicer    TEXT,
  special_servicer   TEXT,
  borrower           TEXT,
  sponsor            TEXT,
  servicer_commentary TEXT,
  detail             JSONB,
  data_as_of         DATE,
  created_at         TIMESTAMPTZ DEFAULT now(),
  updated_at         TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_market_loans_src ON market_loans (source, source_loan_id, deal_name);
CREATE INDEX IF NOT EXISTS idx_market_loans_market ON market_loans (market_id);
CREATE INDEX IF NOT EXISTS idx_market_loans_maturity ON market_loans (maturity_date);
ALTER TABLE market_loans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS market_loans_all ON market_loans;
CREATE POLICY market_loans_all ON market_loans FOR ALL USING (true) WITH CHECK (true);
