-- 61 S Paramus 2025 debt service — derived from monthly mortgage
-- billing statements (loans 327891008 + 327891108).
-- Generated by scripts/extract_61paramus_2025_debt.py

-- Clean any prior debt-service rows for this property/year
DELETE FROM actuals_line_items
 WHERE property_id = 'recqfxJfdqCXCLOuD'
   AND year = 2025
   AND gl_code IN ('7152','7153','7199');

INSERT INTO actuals_line_items (property_id, year, gl_code, account_name, month, amount)
VALUES
  ('recqfxJfdqCXCLOuD', 2025, '7152', '1st Mortgage Interest', 9, 121950.56),
  ('recqfxJfdqCXCLOuD', 2025, '7152', '1st Mortgage Interest', 11, 121950.56),
  ('recqfxJfdqCXCLOuD', 2025, '7153', '2nd Mortgage Interest', 9, 82926.38),
  ('recqfxJfdqCXCLOuD', 2025, '7153', '2nd Mortgage Interest', 11, 82926.38),
  ('recqfxJfdqCXCLOuD', 2025, '7153', '2nd Mortgage Interest', 12, 80251.33),
  ('recqfxJfdqCXCLOuD', 2025, '7199', 'TOTAL DEBT SERVICE', 9, 204876.94),
  ('recqfxJfdqCXCLOuD', 2025, '7199', 'TOTAL DEBT SERVICE', 11, 204876.94),
  ('recqfxJfdqCXCLOuD', 2025, '7199', 'TOTAL DEBT SERVICE', 12, 80251.33);
